<?php

$upgrade_intro = '等级信息将在每日凌晨3点前更新，等级经验仅统计有效流水，1元有效流水=1经验<br>如触发降级，系统将重置等级经验至降级后的初始经验<br>等级更新时，如有晋级礼金将一并发放，请及时关注余额变化';
$rule_intro    = '即日起，您在平台的每一笔有效投注投注永久累计；累计达到等级门槛，即可升级，每晋升一级即可获得相应的礼金，每位会员累计最高可获得66万元的晋级礼金，每月还可领取最高达2万元的月俸禄，可借贷预支俸禄，账号让您一次注册，永久收益！';
$rule_detail   = '1.晋级礼金只要达标系统将自动发放，无需申请，数据次日凌晨更新<br>
2.月俸禄平均分30天领取，若当日不领取，则当日俸禄视为自动放弃，不再做添加处理<br>
3.借款额度为预支次月俸禄，次月开始前若不还清借款，则无法领取次月俸禄<br>
4.每个玩家只能持有一个账户享受本活动，如发现玩家开设多个账号等作弊行为，系统将没收余额且关闭账户<br>
5.每周充值金额不得少于500元，若未达到500元，您的等级将在下周一降1级<br>
6.达到对应等级后，添加客服微信即可领取微信现金红包<br>
7.会员参与任何优惠活动则被视为认同遵守平台所定的规则以及相关规定并愿意受其约束<br>
8.为了避免对文字的理解差异，平台保留对以上方案的解释权和决定权。';

$rule_table = [
    0  => [
        'level_index'  => 0,
        'level_title'  => 'Lv.00',
        'exp_target'   => 0,
        'exp_title'    => '0',
        'gift_upgrade' => 0,
        'gift_month'   => 0,
        'gift_wechat'  => null,
        'gift_total'   => 0,
        'icon'         => 'http://ooo28-public.oss-cn-hangzhou.aliyuncs.com/yl28/config/level0.png',
    ],
    1  => [
        'level_index'  => 1,
        'level_title'  => 'Lv.01',
        'exp_target'   => 200000,
        'exp_title'    => '20万',
        'gift_upgrade' => 58,
        'gift_month'   => 8,
        'gift_wechat'  => null,
        'gift_total'   => 58,
        'icon'         => 'http://ooo28-public.oss-cn-hangzhou.aliyuncs.com/yl28/config/level1.png',
    ],
    2  => [
        'level_index'  => 2,
        'level_title'  => 'Lv.02',
        'exp_target'   => 500000,
        'exp_title'    => '50万',
        'gift_upgrade' => 88,
        'gift_month'   => 30,
        'gift_wechat'  => null,
        'gift_total'   => 146,
        'icon'         => 'http://ooo28-public.oss-cn-hangzhou.aliyuncs.com/yl28/config/level2.png',
    ],
    3  => [
        'level_index'  => 3,
        'level_title'  => 'Lv.03',
        'exp_target'   => 1000000,
        'exp_title'    => '100万',
        'gift_upgrade' => 128,
        'gift_month'   => 50,
        'gift_wechat'  => null,
        'gift_total'   => 274,
        'icon'         => 'http://ooo28-public.oss-cn-hangzhou.aliyuncs.com/yl28/config/level3.png',
    ],
    4  => [
        'level_index'  => 4,
        'level_title'  => 'Lv.04',
        'exp_target'   => 2000000,
        'exp_title'    => '200万',
        'gift_upgrade' => 288,
        'gift_month'   => 80,
        'gift_wechat'  => null,
        'gift_total'   => 562,
        'icon'         => 'http://ooo28-public.oss-cn-hangzhou.aliyuncs.com/yl28/config/level4.png',
    ],
    5  => [
        'level_index'  => 5,
        'level_title'  => 'Lv.05',
        'exp_target'   => 3000000,
        'exp_title'    => '300万',
        'gift_upgrade' => 328,
        'gift_month'   => 100,
        'gift_wechat'  => null,
        'gift_total'   => 890,
        'icon'         => 'http://ooo28-public.oss-cn-hangzhou.aliyuncs.com/yl28/config/level5.png',
    ],
    6  => [
        'level_index'  => 6,
        'level_title'  => 'Lv.06',
        'exp_target'   => 5000000,
        'exp_title'    => '500万',
        'gift_upgrade' => 588,
        'gift_month'   => 150,
        'gift_wechat'  => 88,
        'gift_total'   => 1478,
        'icon'         => 'http://ooo28-public.oss-cn-hangzhou.aliyuncs.com/yl28/config/level6.png',
    ],
    7  => [
        'level_index'  => 7,
        'level_title'  => 'Lv.07',
        'exp_target'   => 7000000,
        'exp_title'    => '700万',
        'gift_upgrade' => 620,
        'gift_month'   => 200,
        'gift_wechat'  => null,
        'gift_total'   => 2098,
        'icon'         => 'http://ooo28-public.oss-cn-hangzhou.aliyuncs.com/yl28/config/level7.png',
    ],
    8  => [
        'level_index'  => 8,
        'level_title'  => 'Lv.08',
        'exp_target'   => 10000000,
        'exp_title'    => '1000万',
        'gift_upgrade' => 888,
        'gift_month'   => 260,
        'gift_wechat'  => null,
        'gift_total'   => 2986,
        'icon'         => 'http://ooo28-public.oss-cn-hangzhou.aliyuncs.com/yl28/config/level.png',
    ],
    9  => [
        'level_index'  => 9,
        'level_title'  => 'Lv.09',
        'exp_target'   => 13000000,
        'exp_title'    => '1300万',
        'gift_upgrade' => 910,
        'gift_month'   => 300,
        'gift_wechat'  => null,
        'gift_total'   => 3896,
        'icon'         => 'http://ooo28-public.oss-cn-hangzhou.aliyuncs.com/yl28/config/level.png',
    ],
    10 => [
        'level_index'  => 10,
        'level_title'  => 'Lv.10',
        'exp_target'   => 16000000,
        'exp_title'    => '1600万',
        'gift_upgrade' => 988,
        'gift_month'   => 400,
        'gift_wechat'  => null,
        'gift_total'   => 4884,
        'icon'         => 'http://ooo28-public.oss-cn-hangzhou.aliyuncs.com/yl28/config/level.png',
    ],
    11 => [
        'level_index'  => 11,
        'level_title'  => 'Lv.11',
        'exp_target'   => 20000000,
        'exp_title'    => '2000万',
        'gift_upgrade' => 1288,
        'gift_month'   => 600,
        'gift_wechat'  => 288,
        'gift_total'   => 6172,
        'icon'         => 'http://ooo28-public.oss-cn-hangzhou.aliyuncs.com/yl28/config/level.png',
    ],
    12 => [
        'level_index'  => 12,
        'level_title'  => 'Lv.12',
        'exp_target'   => 25000000,
        'exp_title'    => '2500万',
        'gift_upgrade' => 1588,
        'gift_month'   => 700,
        'gift_wechat'  => null,
        'gift_total'   => 7760,
        'icon'         => 'http://ooo28-public.oss-cn-hangzhou.aliyuncs.com/yl28/config/level.png',
    ],
    13 => [
        'level_index'  => 13,
        'level_title'  => 'Lv.13',
        'exp_target'   => 30000000,
        'exp_title'    => '3000万',
        'gift_upgrade' => 1888,
        'gift_month'   => 800,
        'gift_wechat'  => null,
        'gift_total'   => 9648,
        'icon'         => 'http://ooo28-public.oss-cn-hangzhou.aliyuncs.com/yl28/config/level.png',
    ],
    14 => [
        'level_index'  => 14,
        'level_title'  => 'Lv.14',
        'exp_target'   => 35000000,
        'exp_title'    => '3500万',
        'gift_upgrade' => 2888,
        'gift_month'   => 900,
        'gift_wechat'  => null,
        'gift_total'   => 12536,
        'icon'         => 'http://ooo28-public.oss-cn-hangzhou.aliyuncs.com/yl28/config/level.png',
    ],
    15 => [
        'level_index'  => 15,
        'level_title'  => 'Lv.15',
        'exp_target'   => 40000000,
        'exp_title'    => '4000万',
        'gift_upgrade' => 3888,
        'gift_month'   => 1000,
        'gift_wechat'  => 888,
        'gift_total'   => 16424,
        'icon'         => 'http://ooo28-public.oss-cn-hangzhou.aliyuncs.com/yl28/config/level.png',
    ],
    16 => [
        'level_index'  => 16,
        'level_title'  => 'Lv.16',
        'exp_target'   => 50000000,
        'exp_title'    => '5000万',
        'gift_upgrade' => 5888,
        'gift_month'   => 1200,
        'gift_wechat'  => null,
        'gift_total'   => 22312,
        'icon'         => 'http://ooo28-public.oss-cn-hangzhou.aliyuncs.com/yl28/config/level.png',
    ],
    17 => [
        'level_index'  => 17,
        'level_title'  => 'Lv.17',
        'exp_target'   => 70000000,
        'exp_title'    => '7000万',
        'gift_upgrade' => 8888,
        'gift_month'   => 1400,
        'gift_wechat'  => null,
        'gift_total'   => '3.12万',
        'icon'         => 'http://ooo28-public.oss-cn-hangzhou.aliyuncs.com/yl28/config/level.png',
    ],
    18 => [
        'level_index'  => 18,
        'level_title'  => 'Lv.18',
        'exp_target'   => 90000000,
        'exp_title'    => '9000万',
        'gift_upgrade' => 10000,
        'gift_month'   => 1800,
        'gift_wechat'  => null,
        'gift_total'   => '4.12万',
        'icon'         => 'http://ooo28-public.oss-cn-hangzhou.aliyuncs.com/yl28/config/level.png',
    ],
    19 => [
        'level_index'  => 19,
        'level_title'  => 'Lv.19',
        'exp_target'   => 100000000,
        'exp_title'    => '1.00亿',
        'gift_upgrade' => 12000,
        'gift_month'   => 2300,
        'gift_wechat'  => 2000,
        'gift_total'   => '5.32万',
        'icon'         => 'http://ooo28-public.oss-cn-hangzhou.aliyuncs.com/yl28/config/level.png',
    ],
    20 => [
        'level_index'  => 20,
        'level_title'  => 'Lv.20',
        'exp_target'   => 150000000,
        'exp_title'    => '1.50亿',
        'gift_upgrade' => 15000,
        'gift_month'   => 2700,
        'gift_wechat'  => null,
        'gift_total'   => '6.82万',
        'icon'         => 'http://ooo28-public.oss-cn-hangzhou.aliyuncs.com/yl28/config/level.png',
    ],
    21 => [
        'level_index'  => 21,
        'level_title'  => 'Lv.21',
        'exp_target'   => 200000000,
        'exp_title'    => '2.00亿',
        'gift_upgrade' => 20000,
        'gift_month'   => 3300,
        'gift_wechat'  => null,
        'gift_total'   => '8.82万',
        'icon'         => 'http://ooo28-public.oss-cn-hangzhou.aliyuncs.com/yl28/config/level.png',
    ],
    22 => [
        'level_index'  => 22,
        'level_title'  => 'Lv.22',
        'exp_target'   => 250000000,
        'exp_title'    => '2.50亿',
        'gift_upgrade' => 25000,
        'gift_month'   => 4500,
        'gift_wechat'  => null,
        'gift_total'   => '11.32万',
        'icon'         => 'http://ooo28-public.oss-cn-hangzhou.aliyuncs.com/yl28/config/level.png',
    ],
    23 => [
        'level_index'  => 23,
        'level_title'  => 'Lv.23',
        'exp_target'   => 300000000,
        'exp_title'    => '3.00亿',
        'gift_upgrade' => 30000,
        'gift_month'   => 5500,
        'gift_wechat'  => 5000,
        'gift_total'   => '14.32万',
        'icon'         => 'http://ooo28-public.oss-cn-hangzhou.aliyuncs.com/yl28/config/level.png',
    ],
    24 => [
        'level_index'  => 24,
        'level_title'  => 'Lv.24',
        'exp_target'   => 350000000,
        'exp_title'    => '3.50亿',
        'gift_upgrade' => 35000,
        'gift_month'   => 6500,
        'gift_wechat'  => null,
        'gift_total'   => '17.82万',
        'icon'         => 'http://ooo28-public.oss-cn-hangzhou.aliyuncs.com/yl28/config/level.png',
    ],
    25 => [
        'level_index'  => 25,
        'level_title'  => 'Lv.25',
        'exp_target'   => 400000000,
        'exp_title'    => '4.00亿',
        'gift_upgrade' => 40000,
        'gift_month'   => 8500,
        'gift_wechat'  => null,
        'gift_total'   => '21.82万',
        'icon'         => 'http://ooo28-public.oss-cn-hangzhou.aliyuncs.com/yl28/config/level.png',
    ],
    26 => [
        'level_index'  => 26,
        'level_title'  => 'Lv.26',
        'exp_target'   => 450000000,
        'exp_title'    => '4.50亿',
        'gift_upgrade' => 45000,
        'gift_month'   => 10000,
        'gift_wechat'  => null,
        'gift_total'   => '26.32万',
        'icon'         => 'http://ooo28-public.oss-cn-hangzhou.aliyuncs.com/yl28/config/level.png',
    ],
    27 => [
        'level_index'  => 27,
        'level_title'  => 'Lv.27',
        'exp_target'   => 500000000,
        'exp_title'    => '5.00亿',
        'gift_upgrade' => 50000,
        'gift_month'   => 12000,
        'gift_wechat'  => null,
        'gift_total'   => '31.32万',
        'icon'         => 'http://ooo28-public.oss-cn-hangzhou.aliyuncs.com/yl28/config/level.png',
    ],
    28 => [
        'level_index'  => 28,
        'level_title'  => 'Lv.28',
        'exp_target'   => 800000000,
        'exp_title'    => '8.00亿',
        'gift_upgrade' => 86800,
        'gift_month'   => 15000,
        'gift_wechat'  => null,
        'gift_total'   => '40.00万',
        'icon'         => 'http://ooo28-public.oss-cn-hangzhou.aliyuncs.com/yl28/config/level.png',
    ],
    29 => [
        'level_index'  => 29,
        'level_title'  => 'Lv.29',
        'exp_target'   => 1000000000,
        'exp_title'    => '10.0亿',
        'gift_upgrade' => 100000,
        'gift_month'   => 17000,
        'gift_wechat'  => null,
        'gift_total'   => '50.00万',
        'icon'         => 'http://ooo28-public.oss-cn-hangzhou.aliyuncs.com/yl28/config/level.png',
    ],
    30 => [
        'level_index'  => 30,
        'level_title'  => 'Lv.30',
        'exp_target'   => 1500000000,
        'exp_title'    => '15.0亿',
        'gift_upgrade' => 160000,
        'gift_month'   => 20000,
        'gift_wechat'  => null,
        'gift_total'   => '66.00万',
        'icon'         => 'http://ooo28-public.oss-cn-hangzhou.aliyuncs.com/yl28/config/level.png',
    ],
];

$result = [
    'upgrade_intro' => $upgrade_intro,
    'rule_intro'    => $rule_intro,
    'rule_detail'   => $rule_detail,
    'rule_table'    => $rule_table,
];

return $result;
